---
#SuperSprint by Yupai config file.

#Add permission (super.sprint) to players who will have Super Sprint.

#Select time in seconds of Speed Effect.
Duration: 15

#Select the amplifier of Speed Effect.
Amplifier: 2

#Visible or not visible (true or false).
Visible: true
...
