---
#SuperSprint by Yupai config file.

#Add permission (super.sprint) to players who will have Super Sprint.

#Select the duration of the Speed Effect.
Duration: 300

#Select the amplifier of the Speed Effect.
Amplifier: 2

#Visible or not visible (true or false).
Visible: true
...
